USE DATABASE AIRLINE_DW;
USE SCHEMA TELEMETRY;

-- Create the immutable target table
CREATE TABLE IF NOT EXISTS BRONZE_B2B_JOINED (
    PNR_LOCATOR VARCHAR,
    FLIGHT_NUMBER VARCHAR,
    BAG_TAG_NUMBER VARCHAR,
    BAGGAGE_LOCATION VARCHAR,
    PASSENGER_GATE VARCHAR,
    BAGGAGE_TIME TIMESTAMP,
    PASSENGER_TIME TIMESTAMP,
    YEAR INT,
    MONTH INT,
    DAY INT
);